name: Build, Push & Make Public Docker Image

on:
  push:
    branches: [main]
    tags: [ 'v*.*.*' ]  # Trigger on semver tags too

permissions:
  contents: read
  packages: write
  id-token: write  # needed for GitHub API auth

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}
      REGISTRY: ghcr.io
      FULL_IMAGE: ghcr.io/${{ github.repository }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          if [ "$TAG" = "" ]; then
            TAG=latest
          fi
          docker build -t $FULL_IMAGE:$TAG .
          docker push $FULL_IMAGE:$TAG

      - name: Make GHCR image public
        uses: stefanzweifel/github-actions-ghcr-public@v1
        with:
          package_name: ${{ env.IMAGE_NAME }}
          package_version: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
